### ISSUE TITLE
Compiled from source, freezing on PSP

### ISSUE THREAD

**Issue by scootalootf2** [gtzampanakis/bookr#1]
EDIT: the work around is to use an older tool chain
eg. https://code.google.com/p/psptoolkit/downloads/list

Is the latest psp-toolchain and libpng from psp-port compatible with the project? After struggling a bit, with stdio.h conflicting with pspdebug.h on void pspDebugScreenPrintf(const char *fmt, ...) in pspdebug vs init pspDebugScreenPrintf(const char *fmt, ...) in stdio which I ended up changing line 182 of stdio.h to stop the compiler from complaining, then including stddef.h into libdjvu's GSmartPointer.h to provide size_t type, compiling libpng from psp-port, bookr did compile at the end, but it's crashing on my PSP 1k...

I tried to compile hello world size applications and they run without problem, not even having pspDebugScreenPrintf( conflicts...

Is the latest toolchain compatible with this? Or which toolchain you're using?

**Comment by scootalootf2** [comment]
I think the issue is from modifying headers to bypass compiler error, but at this point I have no idea how to fix it 
psp-g++ -IC:/Users/Giorgos/psp-ports/trunk/freetype/include -Iutf8 -I. -I/usr/local/pspdev/psp/sdk/include -Imupdf/include -Idjvu/libdjvupsp -I/media/storage/home/scootaloo/pspDev/psp-port/libpng  -G0 -O2 -IC:/Users/Giorgos/psp-ports/trunk/freetype/include -Iutf8 -I. -I/usr/local/pspdev/psp/sdk/include -Imupdf/include -Idjvu/libdjvupsp -I/media/storage/home/scootaloo/pspDev/psp-port/libpng  -G0 -O2 -fno-exceptions -fno-rtti -fexceptions -D_PSP_FW_VERSION=500   -c -o bklayer.o bklayer.cpp
In file included from /usr/local/pspdev/lib/gcc/psp/4.6.4/../../../../psp/include/freetype/config/ftstdlib.h:104:0,
                 from /usr/local/pspdev/lib/gcc/psp/4.6.4/../../../../psp/include/freetype/config/ftconfig.h:43,
                 from /usr/local/pspdev/lib/gcc/psp/4.6.4/../../../../psp/include/freetype/freetype.h:51,
                 from fzfont.h:24,
                 from bklayer.h:29,
                 from bklayer.cpp:23:
/usr/local/pspdev/lib/gcc/psp/4.6.4/../../../../psp/include/stdio.h:182:5: error: declaration of C function ‘int pspDebugScreenPrintf(const char_, ...)’ conflicts with
/usr/local/pspdev/psp/sdk/include/pspdebug.h:49:6: error: previous declaration ‘void pspDebugScreenPrintf(const char_, ...)’ here
make: **\* [bklayer.o] Error 1

**Comment by scootalootf2** [comment]
https://code.google.com/p/psptoolkit/downloads/list
The 'solution' I found, is to use a more antique toolchain, that was really hard to come by...

**Comment by gtzampanakis** [comment]
For this project I have my own toolkit that I have saved somewhere... I had to do some small modifications. But glad to see that you got it working anyway.
